//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.orasystems.libs.utils;

import android.content.Context;
import android.view.animation.AnimationUtils;

public final class AnimationsUtils_
    extends AnimationsUtils
{

    private Context context_;

    private AnimationsUtils_(Context context) {
        context_ = context;
        init_();
    }

    public static AnimationsUtils_ getInstance_(Context context) {
        return new AnimationsUtils_(context);
    }

    private void init_() {
        shrinkFromBottomLeftToTopRight = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.shrink_from_bottom_left_to_top_right);
        pushLeftIn = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_left_in);
        growFromTopRightToBottomLeft = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.grow_from_top_right_to_bottom_left);
        pushDownOut = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_down_out);
        shrinkFromBottom = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.shrink_from_bottom);
        appear = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.appear);
        growFromTopLeftToBottomRight = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.grow_from_top_left_to_bottom_right);
        growFromBottomRightToTopLeft = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.grow_from_bottom_right_to_top_left);
        pushRightOut = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_right_out);
        pushUpOut = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_up_out);
        growFromBottom = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.grow_from_bottom);
        fadeIn = AnimationUtils.loadAnimation(context_, android.R.anim.fade_in);
        shrinkFromTopLeftToBottomRight = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.shrink_from_top_left_to_bottom_right);
        ShrinkFromTop = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.shrink_from_top);
        pulse = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.pulse);
        pushDownIn = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_down_in);
        pushUpIn = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_up_in);
        rotation = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.rotation);
        rail = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.rail);
        growFromTop = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.grow_from_top);
        pushRightIn = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_right_in);
        shrinkFromTopRightToBottomLeft = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.shrink_from_top_right_to_bottom_left);
        pushLeftOut = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.push_left_out);
        growFromBottomLeftToTopRight = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.grow_from_bottom_left_to_top_right);
        fadeOut = AnimationUtils.loadAnimation(context_, android.R.anim.fade_out);
        shrinkFromBottomRightToTopLeft = AnimationUtils.loadAnimation(context_, com.orasystems.libs.utils.R.anim.shrink_from_bottom_right_to_top_left);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
