//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.orasystems.libs.utils;

import android.content.Context;
import com.orasystems.libs.utils.preferences.AtalhoPreferences_;

public final class AtalhoManager_
    extends AtalhoManager
{

    private Context context_;

    private AtalhoManager_(Context context) {
        context_ = context;
        init_();
    }

    public static AtalhoManager_ getInstance_(Context context) {
        return new AtalhoManager_(context);
    }

    private void init_() {
        prefAtalho = new AtalhoPreferences_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
