//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.orasystems.libs.utils;

import android.app.Activity;
import android.content.Context;
import android.util.Log;
import com.orasystems.libs.utils.async.AsyncUtils_;

public final class DownloaderUtils_
    extends DownloaderUtils
{

    private Context context_;

    private DownloaderUtils_(Context context) {
        context_ = context;
        init_();
    }

    public static DownloaderUtils_ getInstance_(Context context) {
        return new DownloaderUtils_(context);
    }

    private void init_() {
        if (context_ instanceof Activity) {
            activity = ((Activity) context_);
        } else {
            Log.w("DownloaderUtils_", (("Due to Context class "+ context_.getClass().getSimpleName())+", the @RootContext Activity won't be populated"));
        }
        asyncTaskHorizontal = AsyncUtils_.getInstance_(context_);
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
