//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.orasystems.libs.utils.preferences;

import android.content.Context;
import android.content.SharedPreferences;
import org.androidannotations.api.sharedpreferences.BooleanPrefEditorField;
import org.androidannotations.api.sharedpreferences.BooleanPrefField;
import org.androidannotations.api.sharedpreferences.EditorHelper;
import org.androidannotations.api.sharedpreferences.SharedPreferencesHelper;

public final class AtalhoPreferences_
    extends SharedPreferencesHelper
{


    public AtalhoPreferences_(Context context) {
        super(context.getSharedPreferences((getLocalClassName(context)+"_AtalhoPreferences"), 0));
    }

    public AtalhoPreferences_.AtalhoPreferencesEditor_ edit() {
        return new AtalhoPreferences_.AtalhoPreferencesEditor_(getSharedPreferences());
    }

    private static String getLocalClassName(Context context) {
        String packageName = context.getPackageName();
        String className = context.getClass().getName();
        int packageLen = packageName.length();
        if (((!className.startsWith(packageName))||(className.length()<= packageLen))||(className.charAt(packageLen)!= '.')) {
            return className;
        }
        return className.substring((packageLen + 1));
    }

    public BooleanPrefField atalhoCriado() {
        return booleanField("atalhoCriado", false);
    }

    public final static class AtalhoPreferencesEditor_
        extends EditorHelper<AtalhoPreferences_.AtalhoPreferencesEditor_>
    {


        AtalhoPreferencesEditor_(SharedPreferences sharedPreferences) {
            super(sharedPreferences);
        }

        public BooleanPrefEditorField<AtalhoPreferences_.AtalhoPreferencesEditor_> atalhoCriado() {
            return booleanField("atalhoCriado");
        }

    }

}
