//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.2.
//


package com.orasystems.libs.utils.async;

import android.app.Activity;
import android.content.Context;
import android.graphics.drawable.Drawable;
import android.os.Handler;
import android.os.Looper;

public final class AsyncUtils_
    extends AsyncUtils
{

    private Context context_;
    private Handler handler_ = new Handler(Looper.getMainLooper());

    private AsyncUtils_(Context context) {
        context_ = context;
        init_();
    }

    public static AsyncUtils_ getInstance_(Context context) {
        return new AsyncUtils_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

    @java.lang.Override
    public void showProgressBar(final Activity activity, final String title, final String message, final int max, final Drawable icon, final boolean setCancelable, final boolean setIndeterminate, final boolean progressHorizontal) {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                AsyncUtils_.super.showProgressBar(activity, title, message, max, icon, setCancelable, setIndeterminate, progressHorizontal);
            }

        }
        );
    }

    @java.lang.Override
    public void atualizaProgressDialog(final GenericAsyncTask asyncTask, final String message, final int progress) {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                AsyncUtils_.super.atualizaProgressDialog(asyncTask, message, progress);
            }

        }
        );
    }

    @java.lang.Override
    public void hideProgressBar() {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                AsyncUtils_.super.hideProgressBar();
            }

        }
        );
    }

    @java.lang.Override
    public void publishProgress(final int progress, final String message) {
        handler_.post(new Runnable() {


            @java.lang.Override
            public void run() {
                AsyncUtils_.super.publishProgress(progress, message);
            }

        }
        );
    }

}
